# @package _global_
defaults:
  - override /hydra/sweeper: nevergrad


optimized_metric: "val/MSE"

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_nevergrad_sweeper.nevergrad_sweeper.NevergradSweeper
    optim:
      # name of the nevergrad optimizer to use
      # OnePlusOne is good at low budget, but may converge early
      optimizer: NGOpt
      # total number of function evaluations to perform
      budget: 100
      # number of parallel workers for performing function evaluations
      num_workers: 1
      maximize: false  # comment out for maximization
    # default parametrization of the search space
    parametrization:
      datamodule.batch_size:
        lower: 64
        upper: 256
        integer: True
      model.leaky_relu_slope:
        init: 0.01
        lower: 0.001
        upper: 0.21
        step: 0.05
      model.dropout_proba:
       init: 0.1
       step: 0.1
       lower: 0.05
       upper: 0.6
      model.lr:
        init: 0.02
        step: 2.0
        log: True

error: False