program: train.py

project: template-tests

description: "sweepy_sweep"

method: bayes

metric:
  name: val/MSE_best
  goal: minimize

parameters:
  model.lr:
    distribution: uniform
    min: 0.0001
    max: 0.1
  datamodule.batch_size:
    values: [32, 64, 128]


command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - experiment=autoencoder