_target_: src.models.autoencoder.Autoencoder
enc_in_features: 18
enc_hidden_features: [128, 128, 128]
enc_out_features: 2
dec_in_features: 2
dec_hidden_features: [128, 128, 128]
dec_out_features: 18
# HYPERPARAMETERS
leaky_relu_slope: 0.3
dropout_proba: 0.5
lr: 0.0001