_target_: src.models.autoencoder_regressor.AutoencoderRegressor
checkpoint_path: ${original_work_dir}/logs/experiments/
reg_in_features: 2   #! has to be same as the latent dimension size of the Autoencoder
reg_hidden_features: [128, 128, 128] 
reg_out_features: 1
# HYPERPARAMETERS
leaky_relu_slope: 0.2
dropout_proba: 0.3
lr: 0.0001