_target_: src.models.autoencoder.Autoencoder

encoder:
  _target_: src.models.modules.dense.FCN
  input_size: 18
  lin1_size: 256
  lin2_size: 128
  lin3_size: 64
  lin4_size: 32
  output_size: 16
decoder:
  _target_: src.models.modules.dense.FCN
  input_size: 16
  lin1_size: 32
  lin2_size: 64
  lin3_size: 128
  lin4_size: 256
  output_size: 18