_target_: src.models.autoencoder.Autoencoder
enc_in_features: 18
enc_hidden_features: [512, 512, 512]
enc_out_features: 10
dec_in_features: 10
dec_hidden_features: [512, 512, 512]
dec_out_features: 18
# HYPERPARAMETERS
leaky_relu_slope: 0.3
dropout_proba: 0.5
lr: 0.0001