_target_: src.models.deterministic_vae.VAEDeterministicPredictor
vae_checkpoint_path: ${original_work_dir}/logs/experiments/
reg_in_features: 2  #! this must be equal to the latent dim of the used VAE
reg_hidden_features: [128, 128, 128]
reg_out_features: 1
leaky_relu_slope: 0.2
dropout_proba: 0.5
lr: 0.002