_target_: src.models.srgan.SRGAN
gen_in_features: 100  # size of random noise for generator
gen_hidden_features: [128, 128, 128]
gen_out_features: 18
dis_in_features: 18
dis_hidden_features: [128, 128, 128]
dis_out_features: 1
# HYPERPARAMETERS
supervised_loss_multiplier: 0.01
unsupervised_loss_multiplier: 0.01
matching_loss_multiplier: 0.01
contrasting_loss_multiplier: 0.01
gradient_penalty_multiplier: 0.01
leaky_relu_slope: 0.2
dropout_proba: 0.5
lr: 0.002