_target_: src.models.ssdkl.SemiSupervisedDeepKernelLearning
enc_in_features: 18
enc_hidden_features: [512, 512, 512]
enc_out_features: 2
variance_loss_multiplier: 10.0
leaky_relu_slope: 0.01
dropout_proba: 0.2
lr: 0.0001