_target_: src.datamodules.datamodules.BuzzDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
n_samples_train_labeled: 500
val_proportion: 0.9
n_samples_test: 1000
num_workers: 0
pin_memory: False