_target_: src.datamodules.datamodules.ElectricDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
split_mode: "relative"
split:
  - 0.8
  - 0.05
  - 0.9
num_workers: 0
pin_memory: False